# Generated by Django 3.0.4 on 2020-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eNumber', models.CharField(max_length=100, null=True)),
                ('Assigned_User', models.CharField(max_length=100, null=True)),
                ('Seniorty_Date', models.DateField(null=True)),
                ('Computer_Name', models.CharField(max_length=100, null=True)),
                ('Asset_Tag', models.IntegerField(null=True)),
                ('Service_Tag', models.CharField(max_length=100, null=True)),
                ('Model_Name', models.CharField(max_length=100, null=True)),
                ('Warranty_EndDate', models.DateField(null=True)),
                ('Warranty_Status', models.CharField(choices=[('Out Of Warranty', 'Out Of Warranty'), ('In Warranty', 'In Warranty')], default='In Warranty', max_length=100, null=True)),
                ('ModelBrand_Name', models.CharField(choices=[('DELL', 'DELL'), ('Hewlett Packard', 'Hewlett Pckard')], default='DELL', max_length=100, null=True)),
                ('ModelParent_Name', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], default='DELL', max_length=100, null=True)),
                ('Docking_Station', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('Secreen1_Model', models.CharField(max_length=100, null=True)),
                ('Secreen1_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Secreen2_Model', models.CharField(max_length=100, null=True)),
                ('Secreen2_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Model_USBheadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_USBheadset', models.IntegerField(null=True)),
                ('Model_DeskPhoneHeadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_DeskPhone', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eNumber', models.CharField(max_length=100, null=True)),
                ('Assigned_User', models.CharField(max_length=100, null=True)),
                ('Seniorty_Date', models.DateField(null=True)),
                ('Computer_Name', models.CharField(max_length=100, null=True)),
                ('Asset_Tag', models.IntegerField(null=True)),
                ('Service_Tag', models.CharField(max_length=100, null=True)),
                ('Model_Name', models.CharField(max_length=100, null=True)),
                ('Warranty_EndDate', models.DateField(null=True)),
                ('Warranty_Status', models.CharField(choices=[('Out Of Warranty', 'Out Of Warranty'), ('In Warranty', 'In Warranty')], default='In Warranty', max_length=100, null=True)),
                ('ModelBrand_Name', models.CharField(choices=[('DELL', 'DELL'), ('Hewlett Packard', 'Hewlett Pckard')], default='DELL', max_length=100, null=True)),
                ('ModelParent_Name', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], default='DELL', max_length=100, null=True)),
                ('Docking_Station', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('Secreen1_Model', models.CharField(max_length=100, null=True)),
                ('Secreen1_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Secreen2_Model', models.CharField(max_length=100, null=True)),
                ('Secreen2_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Model_USBheadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_USBheadset', models.IntegerField(null=True)),
                ('Model_DeskPhoneHeadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_DeskPhone', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eNumber', models.CharField(max_length=100, null=True)),
                ('Assigned_User', models.CharField(max_length=100, null=True)),
                ('Seniorty_Date', models.DateField(null=True)),
                ('Computer_Name', models.CharField(max_length=100, null=True)),
                ('Asset_Tag', models.IntegerField(null=True)),
                ('Service_Tag', models.CharField(max_length=100, null=True)),
                ('Model_Name', models.CharField(max_length=100, null=True)),
                ('Warranty_EndDate', models.DateField(null=True)),
                ('Warranty_Status', models.CharField(choices=[('Out Of Warranty', 'Out Of Warranty'), ('In Warranty', 'In Warranty')], default='In Warranty', max_length=100, null=True)),
                ('ModelBrand_Name', models.CharField(choices=[('DELL', 'DELL'), ('Hewlett Packard', 'Hewlett Pckard')], default='DELL', max_length=100, null=True)),
                ('ModelParent_Name', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], default='DELL', max_length=100, null=True)),
                ('Docking_Station', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('Secreen1_Model', models.CharField(max_length=100, null=True)),
                ('Secreen1_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Secreen2_Model', models.CharField(max_length=100, null=True)),
                ('Secreen2_ServiceTag', models.CharField(max_length=100, null=True)),
                ('Model_USBheadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_USBheadset', models.IntegerField(null=True)),
                ('Model_DeskPhoneHeadset', models.CharField(choices=[('Jabra UCV - 550', 'Jabra UCV - 550'), ('PLANTRONIC C 420', 'PLANTRONIC C 420'), ('SENNHEISER SC 60 USB CTRL', 'SENNHEISER SC 60 USB CTRL'), ('Jabra UCV - 750', 'Jabra UCV - 750'), ('JABRA - BIZ620', 'JABRA - BIZ620')], max_length=100, null=True)),
                ('SN_DeskPhone', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
