# Generated by Django 3.0.4 on 2020-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIS', '0002_auto_20200424_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='Docking_Station',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Docking_Station',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Docking_Station',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100, null=True),
        ),
    ]
