# Generated by Django 3.0.4 on 2020-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIS', '0003_auto_20200424_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='Computer_Name',
            field=models.CharField(default='EX:EMEA-LP0440', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Computer_Name',
            field=models.CharField(default='EX:EMEA-LP0440', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Computer_Name',
            field=models.CharField(default='EX:EMEA-LP0440', max_length=100, null=True),
        ),
    ]
